-- =========================================================
-- 10 - PROMOTION / CLASS UPGRADE RPCs
-- Creates the missing RPCs used by admin-promotions.html
-- Safe to run more than once.
-- =========================================================

begin;

-- Existing older RPCs may have the same argument signature but a different
-- return type. PostgreSQL cannot change a function return type with
-- CREATE OR REPLACE, so remove the old versions first.
drop function if exists public.admin_student_promotion_history(uuid,bigint);
drop function if exists public.admin_promote_whole_class(uuid,text,text,text,text,text,text);
drop function if exists public.admin_promote_selected_students(uuid,bigint[],text,text,text,text,text);
drop function if exists public.admin_promote_student(uuid,bigint,text,text,text,numeric,text,text);

create table if not exists public.student_promotion_history (
    id bigint generated by default as identity primary key,
    student_id bigint not null,
    from_class text,
    to_class text,
    academic_year text,
    exam_name text,
    result_percentage numeric(6,2),
    decision text not null default 'promoted',
    notes text,
    promoted_by text,
    promoted_at timestamptz not null default now()
);

alter table public.student_promotion_history
    add column if not exists student_id bigint,
    add column if not exists from_class text,
    add column if not exists to_class text,
    add column if not exists academic_year text,
    add column if not exists exam_name text,
    add column if not exists result_percentage numeric(6,2),
    add column if not exists decision text default 'promoted',
    add column if not exists notes text,
    add column if not exists promoted_by text,
    add column if not exists promoted_at timestamptz default now();

create index if not exists student_promotion_history_student_idx
    on public.student_promotion_history(student_id, promoted_at desc);

alter table public.student_promotion_history enable row level security;
revoke all on table public.student_promotion_history from public, anon, authenticated;


create or replace function public.admin_promote_student(
    p_token uuid,
    p_student_id bigint,
    p_to_class text,
    p_academic_year text default null,
    p_exam_name text default null,
    p_result_percentage numeric default null,
    p_decision text default 'promoted',
    p_notes text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_student public."Students"%rowtype;
    v_decision text := lower(btrim(coalesce(p_decision,'promoted')));
    v_to_class text := nullif(btrim(coalesce(p_to_class,'')),'');
    v_session jsonb;
    v_admin text;
begin
    perform public.require_app_admin(p_token);

    if v_decision not in ('promoted','repeat','completed') then
        raise exception 'Invalid promotion decision';
    end if;

    select *
      into v_student
      from public."Students"
     where id = p_student_id
     for update;

    if not found then
        raise exception 'Student not found';
    end if;

    if v_decision = 'promoted' then
        if v_to_class is null then
            raise exception 'Next class is required';
        end if;

        if v_to_class not in (
            'قاعدہ','ناظرہ','ترجمہ','حفظ','تجوید','اعدادیہ','متوسطہ',
            'ثانویہ خاصہ سال اول','ثانویہ خاصہ سال دوم',
            'عالیہ سال اول','عالیہ سال دوم',
            'عالمیہ سال اول','عالمیہ سال دوم / دورۂ حدیث'
        ) then
            raise exception 'Invalid class';
        end if;
    else
        v_to_class := v_student.student_class;
    end if;

    if p_result_percentage is not null
       and (p_result_percentage < 0 or p_result_percentage > 100) then
        raise exception 'Result percentage must be between 0 and 100';
    end if;

    begin
        v_session := public.app_session_validate(p_token);
        v_admin := coalesce(v_session->>'username', v_session->>'account_id', 'admin');
    exception when others then
        v_admin := 'admin';
    end;

    if v_decision = 'promoted' then
        update public."Students"
           set student_class = v_to_class
         where id = p_student_id;
    end if;

    insert into public.student_promotion_history(
        student_id,
        from_class,
        to_class,
        academic_year,
        exam_name,
        result_percentage,
        decision,
        notes,
        promoted_by,
        promoted_at
    )
    values(
        p_student_id,
        v_student.student_class,
        v_to_class,
        nullif(btrim(coalesce(p_academic_year,'')),''),
        nullif(btrim(coalesce(p_exam_name,'')),''),
        p_result_percentage,
        v_decision,
        nullif(btrim(coalesce(p_notes,'')),''),
        v_admin,
        now()
    );

    return jsonb_build_object(
        'ok', true,
        'student_id', p_student_id,
        'from_class', v_student.student_class,
        'to_class', v_to_class,
        'decision', v_decision
    );
end;
$$;


create or replace function public.admin_promote_selected_students(
    p_token uuid,
    p_student_ids bigint[],
    p_to_class text,
    p_academic_year text default null,
    p_exam_name text default null,
    p_decision text default 'promoted',
    p_notes text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_id bigint;
    v_result jsonb;
    v_done integer := 0;
    v_failed integer := 0;
    v_results jsonb := '[]'::jsonb;
begin
    perform public.require_app_admin(p_token);

    if p_student_ids is null or coalesce(array_length(p_student_ids,1),0)=0 then
        raise exception 'No students selected';
    end if;

    foreach v_id in array p_student_ids
    loop
        begin
            v_result := public.admin_promote_student(
                p_token,
                v_id,
                p_to_class,
                p_academic_year,
                p_exam_name,
                null,
                p_decision,
                p_notes
            );

            v_done := v_done + 1;
            v_results := v_results || jsonb_build_array(v_result);

        exception when others then
            v_failed := v_failed + 1;
            v_results := v_results || jsonb_build_array(
                jsonb_build_object(
                    'ok', false,
                    'student_id', v_id,
                    'error', sqlerrm
                )
            );
        end;
    end loop;

    return jsonb_build_object(
        'ok', v_failed = 0,
        'updated', v_done,
        'failed', v_failed,
        'results', v_results
    );
end;
$$;


create or replace function public.admin_promote_whole_class(
    p_token uuid,
    p_from_class text,
    p_to_class text,
    p_academic_year text default null,
    p_exam_name text default null,
    p_decision text default 'promoted',
    p_notes text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_ids bigint[];
    v_result jsonb;
begin
    perform public.require_app_admin(p_token);

    select array_agg(id order by id)
      into v_ids
      from public."Students"
     where student_class = p_from_class;

    if v_ids is null or coalesce(array_length(v_ids,1),0)=0 then
        raise exception 'No students found in this class';
    end if;

    v_result := public.admin_promote_selected_students(
        p_token,
        v_ids,
        p_to_class,
        p_academic_year,
        p_exam_name,
        p_decision,
        p_notes
    );

    return v_result || jsonb_build_object(
        'from_class', p_from_class,
        'to_class', p_to_class
    );
end;
$$;


create or replace function public.admin_student_promotion_history(
    p_token uuid,
    p_student_id bigint
) returns table(
    id bigint,
    student_id bigint,
    from_class text,
    to_class text,
    academic_year text,
    exam_name text,
    result_percentage numeric,
    decision text,
    notes text,
    promoted_by text,
    promoted_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    perform public.require_app_admin(p_token);

    return query
    select
        h.id,
        h.student_id,
        h.from_class,
        h.to_class,
        h.academic_year,
        h.exam_name,
        h.result_percentage,
        h.decision,
        h.notes,
        h.promoted_by,
        h.promoted_at
    from public.student_promotion_history h
    where h.student_id = p_student_id
    order by h.promoted_at desc, h.id desc;
end;
$$;


revoke all on function public.admin_promote_student(uuid,bigint,text,text,text,numeric,text,text) from public;
revoke all on function public.admin_promote_selected_students(uuid,bigint[],text,text,text,text,text) from public;
revoke all on function public.admin_promote_whole_class(uuid,text,text,text,text,text,text) from public;
revoke all on function public.admin_student_promotion_history(uuid,bigint) from public;

grant execute on function public.admin_promote_student(uuid,bigint,text,text,text,numeric,text,text) to anon, authenticated;
grant execute on function public.admin_promote_selected_students(uuid,bigint[],text,text,text,text,text) to anon, authenticated;
grant execute on function public.admin_promote_whole_class(uuid,text,text,text,text,text,text) to anon, authenticated;
grant execute on function public.admin_student_promotion_history(uuid,bigint) to anon, authenticated;

commit;
